sudo: false
language: rust
cache: cargo

# run builds if:
#  - the commit is a push to master (maintainers only)
#  - the commit is a PR on master
if: type = push AND branch = master OR type = pull_request AND branch = master

addons:
  apt:
    packages:
      - libssl-dev

rust:
  - stable
  - 1.31.0 # bump as minimum supported Rust version changes
  - beta
  - nightly

before_script:
  - export PATH=$HOME/.cargo/bin:$PATH
  - cargo install cargo-update || true
  - [ "$TRAVIS_RUST_VERSION" == "nightly" ] && cargo install cargo-tarpaulin || true
  - cargo install-update -a

script:
  - cargo build
  - cargo test
  # - cargo bench
  - cargo doc

after_success:
  - [ "$TRAVIS_RUST_VERSION" == "nightly" ] && cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
