sudo: false
language: rust
cache: cargo

# run builds if:
#  - the build is triggered externally
#  - the commit is a push to master (maintainers only)
#  - the commit is a PR on master
if: type = api \
    OR type = push AND branch = master \
    OR type = pull_request AND branch = master

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      # - binutils-dev # required for --verify on coveralls

rust:
  - nightly
  - beta
  - stable
  - 1.31.0 # bump as minimum supported Rust version changes

before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH

script:
  - travis-cargo build
  - travis-cargo test
  # - travis-cargo bench
  - travis-cargo --only stable doc

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
