sudo: false
language: rust
cache: cargo

# run builds if:
#  - the commit is a push to master (maintainers only)
#  - the commit is a PR on master
if: type = push AND branch = master OR type = pull_request AND branch = master

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake

rust:
  - nightly
  - beta
  - stable
  - 1.31.0 # bump as minimum supported Rust version changes

before_script:
  - export PATH=$HOME/.cargo/bin:$PATH
  - cargo install cargo-update || true
  - cargo install cargo-travis || true
  - cargo install-update -a

script:
  - cargo build
  - cargo test
  # - cargo bench
  - cargo doc

after_success:
  - cargo coveralls

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
